stage: train # train, test, sim
test_traj_ep: 3
folder_name: Diffusion
train_option: chair # ball_chair, ball, chair, dynamic
horizon: 18 # 34, 18
max_detection_num: 32
max_trajectory_length: 115
max_path_length: 100 # 105, 40
n_timesteps: 10
show: True
condition_mode: pre # pre, post
is_sim: False
replan_period: 15
pred_mode: 2d
train_set: ./data/real_image_traj/splited_processed_trajs/train/ # ./data/real_image_traj/automatic_processed_trajs/train/ # ./data/real_image_traj/splited_processed_trajs/train/
valid_set: ./data/real_image_traj/splited_processed_trajs/valid/ # ./data/real_image_traj/automatic_processed_trajs/valid/ # ./data/real_image_traj/splited_processed_trajs/valid/
test_set: ./data/real_image_traj/splited_processed_trajs/test/ # ./data/real_image_traj/automatic_processed_trajs/test/ # ./data/real_image_traj/splited_processed_trajs/test/