eval: False
onscreen_render: False
ckpt_dir: ./CoRL_2024_logs/ACT/video
policy_class: ACT 
task_name: sim_transfer_cube_scripted
kl_weight: 10 
chunk_size: 100 
hidden_dim: 512 
batch_size: 8 
dim_feedforward: 3200
seed: 0
num_epochs: 2000
lr: 0.00001
temporal_agg: False
